-- INSERT INTO dz5db.tasks (description, localDateTime, status) VALUES ('Task 1', CURRENT_TIMESTAMP, 'PROCESSING');
-- INSERT INTO dz5db.tasks (description, localDateTime, status) VALUES ('Task 2', CURRENT_TIMESTAMP, 'CREATE');
-- INSERT INTO dz5db.tasks (description, localDateTime, status) VALUES ('Task 3', CURRENT_TIMESTAMP, 'FINISHED');